stages:
  - lint
  - test
  - name: deploy
    if: branch = master

node_js_defaults: &node_js_defaults
  language: node_js
  node_js: '11'
  cache:
    yarn: true

docker_defaults: &docker_defaults
  language: generic
  services:
    - docker

jobs:
  include:
    - stage: lint
      <<: *node_js_defaults
      script: exit 0
